# Generated by Django 4.0.6 on 2022-07-25 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_rename_unicode_hospital_code'),
        ('account', '0004_remove_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='object_id',
        ),
        migrations.AddField(
            model_name='user',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.insurance'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'БАНК'), (2, 'КЛИЕНТ')], default=1),
        ),
    ]
