# Generated by Django 4.0.6 on 2022-07-25 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0005_alter_customerinsurance_card_number'),
        ('account', '0005_remove_user_content_type_remove_user_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_management.customer'),
        ),
    ]
