# Generated by Django 4.0.6 on 2022-08-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_rename_unicode_hospital_code'),
        ('account', '0006_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.hospital'),
        ),
    ]
