# Generated by Django 4.0.6 on 2022-09-29 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0003_invoice_doctor_signature'),
        ('document_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacheddocument',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_management.invoice'),
        ),
    ]
