# Generated by Django 4.0.6 on 2022-09-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_management', '0002_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='doctor_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
