# Generated by Django 4.0.6 on 2022-07-26 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_personal_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorservice',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_personal_cabinet.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorspecialty',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_personal_cabinet.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorspecialty',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_personal_cabinet.specialty'),
        ),
        migrations.AlterField(
            model_name='doctortimetable',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_personal_cabinet.doctor'),
        ),
    ]
