# Generated by Django 4.0.6 on 2022-09-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_rename_unicode_hospital_code'),
        ('customer_personal_cabinet', '0002_alter_doctorservice_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(to='directory.service'),
        ),
    ]
