# Generated by Django 4.0.6 on 2022-10-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_personal_cabinet', '0003_doctor_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='code',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
