# Generated by Django 4.0.6 on 2022-10-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_personal_cabinet', '0005_alter_doctortimetable_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=180)),
                ('program', models.CharField(max_length=180)),
                ('iin', models.CharField(max_length=180)),
            ],
        ),
    ]
