# Generated by Django 4.0.6 on 2022-11-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_personal_cabinet', '0006_payprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorOutsideTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_personal_cabinet.doctor')),
            ],
        ),
    ]
