# Generated by Django 4.0.6 on 2022-11-03 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_personal_cabinet', '0007_doctoroutsidetimetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoroutsidetimetable',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctoroutsidetimetable',
            name='date',
        ),
        migrations.AddField(
            model_name='doctoroutsidetimetable',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
