# Generated by Django 4.0.6 on 2022-07-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='cancel_date',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='customer_insurance',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='date',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='directed_hospital',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='doctor_full_name',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='icd',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='performing_doctor',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='place',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='sending_hospital',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='service',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='type_appeal',
        ),
    ]
