# Generated by Django 4.0.6 on 2022-07-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_hospital_unicode'),
        ('customer_management', '0002_alter_customerinsurance_customer'),
        ('referral_management', '0002_remove_referral_cancel_date_remove_referral_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='customer_management.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='customer_insurance',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='customer_management.customerinsurance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='date',
            field=models.DateField(auto_now_add=True, default='2022-07-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='directed_hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='directed_hospital', to='directory.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='doctor_full_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='icd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.icd'),
        ),
        migrations.AddField(
            model_name='referral',
            name='performing_doctor',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='place',
            field=models.IntegerField(choices=[(1, 'На дому'), (2, 'ПМСП'), (3, 'Амбулаторно'), (4, 'Стационарно')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='sending_hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sending_hospital', to='directory.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='referral_services', to='directory.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='type_appeal',
            field=models.IntegerField(choices=[(1, 'ОМС'), (2, 'ДМС'), (3, 'Платно')], default=1),
            preserve_default=False,
        ),
    ]
