# Generated by Django 4.0.6 on 2022-09-22 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_management', '0003_referral_cancel_date_referral_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
