# Generated by Django 4.0.6 on 2022-10-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_management', '0004_alter_referral_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
