# Generated by Django 4.0.6 on 2023-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_management', '0005_referral_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
