# Generated by Django 4.0.6 on 2022-07-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=180)),
                ('last_name', models.CharField(max_length=180)),
                ('surname', models.CharField(max_length=180)),
                ('national', models.CharField(max_length=180)),
                ('address', models.CharField(max_length=180)),
                ('place_work', models.CharField(max_length=180)),
                ('telephone_number', models.CharField(max_length=180)),
                ('profession', models.CharField(max_length=180)),
                ('iin', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=180)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_management.customer')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.insurance')),
            ],
        ),
    ]
