# Generated by Django 4.0.6 on 2022-07-14 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinsurance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_insurance', to='customer_management.customer'),
        ),
    ]
