# Generated by Django 4.0.6 on 2022-07-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0005_alter_customerinsurance_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='insurer',
            field=models.CharField(default=1, max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='invoice_sum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='limit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customerinsurance',
            name='program',
            field=models.CharField(default=1, max_length=320),
            preserve_default=False,
        ),
    ]
