# Generated by Django 4.0.6 on 2022-11-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0007_alter_customerinsurance_invoice_sum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinsurance',
            name='pay_type',
            field=models.IntegerField(choices=[(1, 'ДМС индивидуальный'), (2, 'ОМС/ДМС перестраховочные')], default=1),
        ),
    ]
