# Generated by Django 4.0.6 on 2023-03-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0008_customerinsurance_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
