# Generated by Django 4.0.6 on 2023-03-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0009_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'Мужчина'), (2, 'Женщина')], max_length=180, null=True),
        ),
    ]
