# Generated by Django 4.0.6 on 2023-03-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0012_customer_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
