# Generated by Django 4.0.6 on 2022-07-14 07:37

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('address', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('bin', models.CharField(blank=True, max_length=180, null=True)),
                ('address', models.CharField(blank=True, max_length=180, null=True)),
                ('iik', models.CharField(blank=True, max_length=180, null=True)),
                ('bik', models.CharField(blank=True, max_length=180, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=180, null=True)),
                ('residency', models.CharField(blank=True, max_length=180, null=True)),
                ('sector_economy', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('bin', models.CharField(blank=True, max_length=180, null=True)),
                ('address', models.CharField(blank=True, max_length=180, null=True)),
                ('iik', models.CharField(blank=True, max_length=180, null=True)),
                ('bik', models.CharField(blank=True, max_length=180, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=180, null=True)),
                ('residency', models.CharField(blank=True, max_length=180, null=True)),
                ('sector_economy', models.CharField(blank=True, max_length=180, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('code', models.CharField(max_length=180, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directory.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ICD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=320)),
                ('code', models.CharField(blank=True, max_length=180, null=True)),
                ('is_impossible', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directory.icd')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
