# Generated by Django 4.0.6 on 2022-07-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='unicode',
            field=models.CharField(default=1, max_length=180, unique=True),
            preserve_default=False,
        ),
    ]
