# Generated by Django 4.0.6 on 2022-07-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_insurance_unicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='unicode',
            field=models.CharField(default=1, max_length=180, unique=True),
            preserve_default=False,
        ),
    ]
