# Generated by Django 4.0.6 on 2022-07-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_hospital_unicode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurance',
            old_name='unicode',
            new_name='code',
        ),
    ]
