# Generated by Django 4.0.6 on 2022-07-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_rename_unicode_insurance_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='unicode',
            new_name='code',
        ),
    ]
