# Generated by Django 4.0.6 on 2022-10-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_rename_unicode_hospital_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='status',
            field=models.IntegerField(choices=[(0, 'Сельская больница'), (1, 'Районная больница'), (2, 'Городская больница')], default=0),
        ),
    ]
